### ISSUE TITLE
AttributeError when fetching articles

### ISSUE THREAD

**Issue by LCPLCat** [AlexFlipnote/ukraine_discord#2]
When running the program the output is this.

> [36m[?][0m 2022-03-07 09:20:03.207320 - Checking for new articles
> [32m[+][0m Fetching all articles and parsing HTML...
> [33m[!][0m   File "C:\Users\A##-pc\Desktop\ukraine_discord-master\index.py", line 182, in main
>     r = fetch("https://liveuamap.com/")
>   File "C:\Users\Alex-pc\Desktop\ukraine_discord-master\index.py", line 164, in fetch
>     "User-Agent": read_json("user_agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64)")
>   File "C:\Users\Alex-pc\Desktop\ukraine_discord-master\index.py", line 81, in read_json
>     return data.get(key, default)
> AttributeError: 'list' object has no attribute 'get'

This repeats as it tries to get new articles.

**Comment by AlexFlipnote** [comment]
Seems like you made a list of the "user_agent" inside the config.json file, it's supposed to be a "" string, not a [] list

**Comment by LCPLCat** [comment]
https://pastebin.com/TAVLR89t This is my current config.json all looks to be right unless I am just stupid

**Comment by AlexFlipnote** [comment]
First of all, make a new webhook URL, you just leaked sensitive data. 

Regardless, you have it wrapped inside [ ] which causes the error.

**Comment by LCPLCat** [comment]
ahh ok and the webhook is censored it's fine
